ARG BASE_IMAGE=ghcr.io/aica-technology/ros2-ws
ARG BASE_TAG=iron
FROM ${BASE_IMAGE}:${BASE_TAG} as ros2-control-build

RUN sudo apt-get update && sudo apt-get install --no-install-recommends -y \
  doxygen \
  librange-v3-dev \
  python3-typeguard \
  python3-jinja2 \
  && sudo rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ROS2_WORKSPACE}/src/ros2_control
WORKDIR ${ROS2_WORKSPACE}/src/ros2_control

RUN git clone -b 3.16.0 --depth 1 https://github.com/ros-controls/ros2_control.git
RUN git clone -b 3.11.0 --depth 1 https://github.com/ros-controls/ros2_controllers.git
# get additional interface dependencies manually
RUN git clone -b 5.0.0 --depth 1 https://github.com/ros-controls/control_msgs.git
RUN git clone -b 1.0.2 --depth 1 https://github.com/pal-robotics/backward_ros.git
RUN git clone -b 3.1.2 --depth 1 https://github.com/ros/diagnostics.git
RUN git clone -b 2.5.0 --depth 1 https://github.com/ros-controls/realtime_tools.git
RUN git clone -b 1.7.0 --depth 1 https://github.com/ros2/rcl_interfaces.git
RUN git clone -b 0.11.0 --depth 1 https://github.com/ros2/test_interface_files.git
RUN git clone -b 1.16.0 --depth 1 https://github.com/ros/angles.git
RUN git clone -b ros2 --depth 1 https://github.com/ros-drivers/ackermann_msgs.git
RUN git clone -b 0.3.3 --depth 1 https://github.com/PickNikRobotics/generate_parameter_library.git
RUN git clone -b 0.2.2 --depth 1 https://github.com/PickNikRobotics/RSL.git
RUN git clone -b 1.0.2 --depth 1 https://github.com/PickNikRobotics/cpp_polyfills.git
RUN git clone -b 3.1.0 --depth 1 https://github.com/ros-controls/control_toolbox.git
RUN git clone -b 0.1.0 --depth 1 https://github.com/ros-controls/kinematics_interface.git

WORKDIR ${ROS2_WORKSPACE}
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; colcon build"
RUN rm -rf ./src


FROM ${BASE_IMAGE}:${BASE_TAG} as final
COPY --from=ros2-control-build / /
