name: 'Build and Push'
description: 'Build the Docker image and push to GitHub Container Registry'
inputs:
  image:
    description: 'The desired image'
    required: false
    default: 'ros2-ws:galactic'
  cl_branch:
    description: 'The branch of control libraries'
    required: false
    default: 'main'
  modulo_branch:
    description: 'The branch of modulo'
    required: false
    default: 'main'
  secret:
    description: 'GitHub Container Registry secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build image
      run: |
        IMAGE_NAME=${{ inputs.image }}
        ROS_VERSION=${IMAGE_NAME#*:}
        WORKSPACE=${IMAGE_NAME%:*}
        WORKSPACE=${WORKSPACE//[-]/_}
        mkdir -p ${WORKSPACE}/config
        cp common/sshd_entrypoint.sh ${WORKSPACE}/config/
        docker build ${WORKSPACE} --file ${WORKSPACE}/Dockerfile \
          --build-arg ROS_VERSION=${ROS_VERSION} \
          --build-arg CL_BRANCH=${{ inputs.cl_branch }} \
          --build-arg MODULO_BRANCH=${{ inputs.modulo_branch }} \
          --tag ${IMAGE_NAME}
      shell: bash

    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.secret }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Push image
      run: |
        IMAGE_NAME=${{ inputs.image }}
        docker tag ${IMAGE_NAME} ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
      shell: bash
