name: Build and Push Multi-Arch Images for Pinocchio

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        required: false
        type: boolean
        default: false

env:
  PINOCCHIO_PATH: pinocchio

jobs:
  check-version:
    name: Check if the version has been updated
    outputs:
      has_changed: ${{ steps.check.outputs.has_changed }}
      version: ${{ steps.versions.outputs.new_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
      - id: versions
        run: |
          set +e
          git show HEAD^:$PINOCCHIO_PATH/VERSION 2>/dev/null
          if [[ $? == 0 ]]; then
            PREV_VERSION=$(git show HEAD^:$PINOCCHIO_PATH/VERSION)
          else
            PREV_VERSION=0.0.0
          fi
          set -e
          NEW_VERSION=$(git show HEAD:$PINOCCHIO_PATH/VERSION)

          echo "prev_version=${PREV_VERSION}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        shell: bash
      - uses: aica-technology/.github/.github/actions/compare-versions@v1.0.2
        id: check
        with:
          previous_version: ${{ steps.versions.outputs.prev_version }}
          new_version: ${{ steps.versions.outputs.new_version }}

  metadata:
    needs: check-version
    if: ${{ needs.check-version.outputs.has_changed == 'true' || inputs.force }}
    runs-on: ubuntu-latest
    name: Metadata
    outputs:
      image_name: ${{ steps.ensure-image.outputs.image_name }}
      image_tags: ${{ steps.tags.outputs.image_tags }}
      build_flags: ${{ steps.tags.outputs.build_flags }}
      git_tag: ${{ steps.tags.outputs.git_tag }}
    steps:
      - uses: aica-technology/.github/.github/actions/ghcr-ensure-prefix@v0.6.0
        id: ensure-image
        with:
          image_name: aica-technology/pinocchio

      - id: tags
        run: |
          BUILD_FLAGS=()
          VERSION_TAG="v${{ needs.check-version.outputs.version }}"
          if [[ "${VERSION_TAG}" == *"-"* ]]; then
            GIT_TAG=""
          else
            GIT_TAG=pinocchio/${VERSION_TAG}
          fi
          IMAGE_TAGS=${VERSION_TAG}
          BUILD_FLAGS+=(--build-arg VERSION=${VERSION_TAG})

          echo "Image tags: ${IMAGE_TAGS}"
          echo "Git tag: ${GIT_TAG}"
          echo "build_flags=${BUILD_FLAGS[@]}" >> $GITHUB_OUTPUT
          echo "image_tags=${IMAGE_TAGS}" >> $GITHUB_OUTPUT
          echo "git_tag=${GIT_TAG}" >> $GITHUB_OUTPUT

  build:
    needs: metadata
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - image: ubuntu-latest
          - image: ubuntu-24.04-arm
            arch: arm64

    runs-on: ${{ matrix.image }}
    name: Build and publish (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v6

      - uses: aica-technology/.github/.github/actions/list-add-suffixes@v0.6.1
        id: merge-tags
        with:
          list: ${{ needs.metadata.outputs.image_tags }}
          suffixes: ${{ matrix.arch }}
          glue_separator: "-"

      - id: arch
        run: |
          BUILD_FLAGS=${{ needs.metadata.outputs.build_flags }}
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            BUILD_FLAGS+=(--build-arg ARCH=aarch64)
          elif [[ "${{ matrix.arch }}" == "amd64" ]]; then
            BUILD_FLAGS+=(--build-arg ARCH=x86_64)
          fi
          echo "build_flags=${BUILD_FLAGS[@]}" >> $GITHUB_OUTPUT

      - uses: aica-technology/.github/.github/actions/ghcr-build@v1.0.4
        with:
          image_name: ${{ needs.metadata.outputs.image_name }}
          image_tags: ${{ steps.merge-tags.outputs.list }}
          build_context_path: $PINOCCHIO_PATH
          dockerfile_path: $PINOCCHIO_PATH/Dockerfile
          build_flags: ${{ steps.arch.outputs.build_flags }}
          token: ${{ secrets.GITHUB_TOKEN }}

  multi-arch:
    runs-on: ubuntu-latest
    name: Merge into a multi-arch image
    needs: [metadata, build]
    steps:
      - uses: aica-technology/.github/.github/actions/ghcr-manifest-merge@v0.6.1
        with:
          image_name: ${{ needs.metadata.outputs.image_name }}
          image_tags: ${{ needs.metadata.outputs.image_tags }}
          archs: amd64,arm64
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create git tag
        if: ${{ needs.metadata.outputs.git_tag != '' }}
        uses: aica-technology/.github/.github/actions/git-tag@v0.8.1
        with:
          tag: ${{ needs.metadata.outputs.git_tag }}
