name: Scheduled Build and Push Multi-Arch Images (develop branches)

# Run scheduled workflow
on:
  schedule:
    - cron: '05 4 * * 1,4' # corresponds to Wednesday and Saturday
  workflow_dispatch:

jobs:
  check-upstream:
    uses: ./.github/workflows/reusable-check-upstream.yml
    with:
      upstream_branch: develop
      ci_branch: ci
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}
