name: Check for updated control libraries

# Run scheduled workflow
on:
  schedule:
   - cron: '20 3,13 * * MON-FRI'
  workflow_dispatch:

env:
  CI_BRANCH: 'ci'

jobs:

  check-hash:
    runs-on: ubuntu-latest
    name: Check latest hash on control libraries
    outputs:
      rebuild: ${{ steps.check.outputs.rebuild }}
      id: ${{ steps.check.outputs.id }}
    steps:
      - name: Checkout CI branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CI_BRANCH }}

      - name: Check lastest hash on develop branch
        id: check
        run: |
          NEW_HASH=$(git ls-remote https://github.com/epfl-lasa/control-libraries.git develop | awk '{ print $1 }')
          OLD_HASH=$(cat ./control-libraries-hash || echo '')
          if [ "${NEW_HASH}" = "${OLD_HASH}" ]; then
            echo "The ros2-control-libraries image is up to date."
            echo "::set-output name=rebuild::false"
          else
            echo "Control libraries have new commits, rebuilding image now..."
            echo "::set-output name=rebuild::true"
            echo "::set-output name=id::${NEW_HASH}"
          fi

  rebuild-image:
    needs: check-hash
    runs-on: ubuntu-latest
    name: Rebuild ros2-control-libraries image
    if: ${{ needs.check-hash.outputs.rebuild == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build new image
        uses: ./.github/actions/build-push
        with:
          image: ros2-control-libraries:foxy
          cl_branch: develop
          secret: ${{ secrets.GITHUB_TOKEN }}

  write-hash:
    needs: [check-hash, rebuild-image]
    runs-on: ubuntu-latest
    name: Write new hash to file
    steps:
      - name: Checkout CI branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.CI_BRANCH }}

      - name: Write new hash to file and push to 'ci' branch
        run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch && git checkout main && git pull && git checkout ci && git rebase
          echo ${{ needs.check-hash.outputs.id }} > ./control-libraries-hash
          git add ./control-libraries-hash && git commit -m "Update hash of control libraries" && git push
