name: Scheduled Build and Push Multi-Arch Images (main branches)

# Run scheduled workflow
on:
  schedule:
    - cron: '05 4 * * 1' # corresponds to Saturday
  workflow_dispatch:

jobs:
  check-upstream:
    uses: ./.github/workflows/reusable-check-upstream.yml
    with:
      upstream_branch: main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
