name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'The desired workspace (e.g. ros2-control-libraries)'
        required: true
      ros_version:
        description: 'The ROS distribution to use'
        required: false
        default: 'galactic'
      cl_branch:
        description: 'The branch of control libraries'
        required: false
        default: 'main'
      modulo_branch:
        description: 'The branch of modulo'
        required: false
        default: 'main'
      base_tag:
        description: 'The tag of the base image to use (if left empty, the tag is the ROS version)'
        required: false
        default: ''
      output_tag:
        description: 'The tag for the output image (if left empty, the base tag is used)'
        required: false
        default: ''

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          workspace: ${{ github.event.inputs.workspace }}
          ros_version: ${{ github.event.inputs.ros_version }}
          cl_branch: ${{ github.event.inputs.cl_branch }}
          modulo_branch: ${{ github.event.inputs.modulo_branch }}
          base_tag: ${{ github.event.inputs.base_tag }}
          output_tag: ${{ github.event.inputs.output_tag }}
          secret: ${{ secrets.GITHUB_TOKEN }}
