name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'The desired workspace (e.g. ros2-control-libraries)'
        required: true
        options:
          - 'ros2-ws'
          - 'ros2-control-libraries'
          - 'ros2-modulo'
          - 'ros2-modulo-control'
      architecture:
        description: 'The desired architecture to build [`amd64` or `amd64 & arm64`]'
        required: true
        default: 'amd64'
        options:
          - 'amd64'
          - 'amd64 & arm64'
      base_tag:
        description: 'The tag of the base image to use'
        required: false
        default: 'galactic'
      cl_branch:
        description: 'The branch of control libraries'
        required: false
        default: 'main'
      dockerfile_extension:
        description: 'The optional extension of the Dockerfile for variant images'
        required: false
        default: ''
      modulo_branch:
        description: 'The branch of modulo'
        required: false
        default: 'main'
      output_tag:
        description: 'The tag for the output image (if left empty, the base tag is used)'
        required: false
        default: ''
      write_image_hash:
        description: 'Write image SHA256 hash to file (set to false for temporary or test images)'
        required: false
        default: 'true'
        options:
          - 'true'
          - 'false'

env:
  CI_BRANCH: 'ci'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        if: ${{ github.event.inputs.architecture == 'amd64' }}
        uses: ./.github/actions/build-push
        with:
          workspace: ${{ github.event.inputs.workspace }}
          base_tag: ${{ github.event.inputs.base_tag }}
          cl_branch: ${{ github.event.inputs.cl_branch }}
          modulo_branch: ${{ github.event.inputs.modulo_branch }}
          output_tag: ${{ github.event.inputs.output_tag }}
          write_image_hash: ${{ github.event.inputs.write_image_hash }}
          ci_branch: ${{ env.CI_BRANCH }}
          secret: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (Multi-Arch)
        if: ${{ github.event.inputs.architecture == 'amd64 & arm64' }}
        uses: ./.github/actions/build-push-multi-arch
        with:
          workspace: ${{ github.event.inputs.workspace }}
          base_tag: ${{ github.event.inputs.base_tag }}
          cl_branch: ${{ github.event.inputs.cl_branch }}
          modulo_branch: ${{ github.event.inputs.modulo_branch }}
          output_tag: ${{ github.event.inputs.output_tag }}
          write_image_hash: ${{ github.event.inputs.write_image_hash }}
          ci_branch: ${{ env.CI_BRANCH }}
          secret: ${{ secrets.GITHUB_TOKEN }}
