name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'The desired image (<workspace>:<ros_distro>)'
        required: true
      cl_branch:
        description: 'If set, the desired branch of control libraries for the combined image'
        required: false
        default: 'develop'
      modulo_branch:
        description: 'If set, the desired branch of modulo for the combined image'
        required: false
        default: 'develop'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: ${{ github.event.inputs.image }}
          cl_branch: ${{ github.event.inputs.cl_branch }}
          modulo_branch: ${{ github.event.inputs.modulo_branch }}
          secret: ${{ secrets.GITHUB_TOKEN }}
