name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'The desired workspace'
        required: true
        type: choice
        options:
          - ros2-ws
          - ros2-control
      base_tag:
        description: 'The tag of the base image to use'
        required: false
        default: 'humble'
      output_tag:
        description: 'The tag for the output image (if left empty, the base tag is used)'
        required: false
        default: ''
      dockerfile_extension:
        description: 'The optional extension of the Dockerfile for variant images'
        required: false
        default: ''

jobs:
  build-push:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      workspace: ${{ inputs.workspace }}
      base_tag: ${{ inputs.base_tag }}
      output_tag: ${{ inputs.output_tag }}
      dockerfile_extension: ${{ inputs.dockerfile_extension }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}