name: Manual Build and Push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'The desired image (aica-technology/<ros_workspace>:<ros_distro>)'
        required: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build and publish ROS image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          image: ${{ github.event.inputs.image }}
          secret: ${{ secrets.GITHUB_TOKEN }}
