name: Reusable workflow for scheduled checks

on:
  workflow_call:
    inputs:
      upstream_branch:
        required: true
        type: string
    secrets:
      token:
        required: true

env:
  CI_BRANCH: 'ci'

jobs:
  check-hash:
    runs-on: ubuntu-latest
    name: Check latest hashes on control libraries and modulo
    outputs:
      cl_rebuild: ${{ steps.check_cl.outputs.rebuild }}
      modulo_rebuild: ${{ steps.check_modulo.outputs.rebuild }}
      image_tag: ${{ steps.parse_tag.outputs.tag }}
    steps:
      - name: Checkout CI branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CI_BRANCH }}

      - name: Parse tag for images
        id: parse_tag
        run: |
          if [[ "${{ inputs.upstream_branch }}" == "main" ]]; then
            IMAGE_TAG=humble
          elif [[ "${{ inputs.upstream_branch }}" == "develop" ]]; then
            IMAGE_TAG=humble-devel
          else
            echo "::error::Invalid upstream branch. Needs to be either 'main' or 'develop'."
            exit 1
          fi
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Check latest hash on control libraries
        id: check_cl
        run: |
          NEW_HASH=$(git ls-remote https://github.com/aica-technology/control-libraries.git ${{ inputs.upstream_branch }} | awk '{ print $1 }')
          OLD_HASH=$(cat ./control-libraries-${{ inputs.upstream_branch }}-hash || echo '')
          if [ "${NEW_HASH}" = "${OLD_HASH}" ]; then
            echo "Control libraries doesn't have new commits."
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "Control libraries have new commits, rebuilding image now..."
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

      - name: Check latest hash on modulo
        id: check_modulo
        run: |
          NEW_HASH=$(git ls-remote https://github.com/aica-technology/modulo.git ${{ inputs.upstream_branch }} | awk '{ print $1 }')
          OLD_HASH=$(cat ./modulo-${{ inputs.upstream_branch }}-hash || echo '')
          if [ "${NEW_HASH}" = "${OLD_HASH}" ]; then
            echo "Modulo doesn't have new commits."
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "Modulo has new commits, rebuilding image now..."
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

  rebuild-cl-humble-image:
    needs: check-hash
    if: needs.check-hash.outputs.cl_rebuild == 'true'
    name: Rebuild ros2-control-libraries humble image
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      workspace: ros2-control-libraries
      base_tag: humble
      output_tag: ${{ needs.check-hash.outputs.image_tag }}
      cl_branch: ${{ inputs.upstream_branch }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  rebuild-modulo-humble-image:
    needs: [ check-hash, rebuild-cl-humble-image ]
    if: |
      always() &&
      (needs.rebuild-cl-humble-image.result == 'success' || needs.rebuild-cl-humble-image.result == 'skipped') &&
      (needs.check-hash.outputs.cl_rebuild == 'true' || needs.check-hash.outputs.modulo_rebuild == 'true')
    name: Rebuild ros2-modulo humble image
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      workspace: ros2-modulo
      base_tag: ${{ needs.check-hash.outputs.image_tag }}
      output_tag: ${{ needs.check-hash.outputs.image_tag }}
      modulo_branch: ${{ inputs.upstream_branch }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  rebuild-modulo-control-humble-image:
    needs: [ check-hash, rebuild-modulo-humble-image ]
    if: always() && needs.rebuild-modulo-humble-image.result == 'success'
    name: Rebuild ros2-modulo-control humble image
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      workspace: ros2-modulo-control
      base_tag: ${{ needs.check-hash.outputs.image_tag }}
      output_tag: ${{ needs.check-hash.outputs.image_tag }}
      dockerfile_extension: .humble
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
