name: Reusable workflow to build and push multi-arch toolkit images

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
      build_args:
        required: false
        type: string
        default: ""
      force:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true

env:
  TOOLKITS_PATH: toolkits

jobs:
  check-version:
    name: Check if the version has been updated
    outputs:
      has_changed: ${{ steps.check.outputs.has_changed }}
      version: ${{ steps.versions.outputs.new_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: versions
        run: |
          FILE="$TOOLKITS_PATH/VERSION.${{ inputs.variant }}"
          PREV_VERSION=$(git show HEAD^:"$FILE" 2>/dev/null || echo "0.0.0")
          NEW_VERSION=$(git show HEAD:"$FILE")

          echo "prev_version=${PREV_VERSION}" >> $GITHUB_OUTPUT
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - uses: aica-technology/.github/.github/actions/compare-versions@v1.0.2
        id: check
        with:
          previous_version: ${{ steps.versions.outputs.prev_version }}
          new_version: ${{ steps.versions.outputs.new_version }}

  metadata:
    needs: check-version
    if: ${{ needs.check-version.outputs.has_changed == 'true' || inputs.force }}
    runs-on: ubuntu-latest
    name: Metadata
    outputs:
      image_name: ${{ steps.ensure-image.outputs.image_name }}
      image_tags: ${{ steps.tags.outputs.image_tags }}
      build_flags: ${{ steps.tags.outputs.build_flags }}
      git_tag: ${{ steps.tags.outputs.git_tag }}
    steps:
      - uses: aica-technology/.github/.github/actions/ghcr-ensure-prefix@v0.6.0
        id: ensure-image
        with:
          image_name: aica-technology/${{ inputs.variant }}-toolkit # TODO: that's my original naming, but perhaps toolkit-${{ inputs.variant }} would be better?

      - id: tags
        run: |
          VERSION_TAG="v${{ needs.check-version.outputs.version }}"

          # TODO: this needs work. We are carrying a lot more tags and we now need to find a format that makes sense for version controlling too
          if [[ "${VERSION_TAG}" == *"-"* ]]; then
            IMAGE_TAGS="${VERSION_TAG},${VERSION_TAG}-${{ inputs.variant }}"
            GIT_TAG=""
          else
            IMAGE_TAGS="${VERSION_TAG},${VERSION_TAG}-${{ inputs.variant }},${{ inputs.variant }}"
            GIT_TAG="${VERSION_TAG}-${{ inputs.variant }}"
          fi

          echo "image_tags=${IMAGE_TAGS}" >> $GITHUB_OUTPUT
          echo "git_tag=${GIT_TAG}" >> $GITHUB_OUTPUT
          echo "build_flags=${{ inputs.build_args }}" >> $GITHUB_OUTPUT

  build:
    needs: metadata
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - image: ubuntu-latest
            arch: amd64
          - image: buildjet-2vcpu-ubuntu-2204-arm
            arch: arm64

    runs-on: ${{ matrix.image }}
    name: Build toolkit (${{ inputs.variant }}) for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3

      - uses: aica-technology/.github/.github/actions/list-add-suffixes@v0.6.1
        id: merge-tags
        with:
          list: ${{ needs.metadata.outputs.image_tags }}
          suffixes: ${{ matrix.arch }}
          glue_separator: "-"

      - uses: aica-technology/.github/.github/actions/ghcr-build@v0.6.1
        with:
          image_name: ${{ needs.metadata.outputs.image_name }}
          image_tags: ${{ steps.merge-tags.outputs.list }}
          build_context_path: toolkits
          dockerfile_path: toolkits/Dockerfile.${{ inputs.variant }}
          build_flags: ${{ needs.metadata.outputs.build_flags }}
          token: ${{ secrets.token }}

  multi-arch:
    runs-on: ubuntu-latest
    name: Merge into a multi-arch image
    needs: [metadata, build]
    steps:
      - uses: aica-technology/.github/.github/actions/ghcr-manifest-merge@v0.6.1
        with:
          image_name: ${{ needs.metadata.outputs.image_name }}
          image_tags: ${{ needs.metadata.outputs.image_tags }}
          archs: amd64,arm64
          token: ${{ secrets.token }}

      - name: Create git tag
        if: ${{ needs.metadata.outputs.git_tag != '' }}
        uses: aica-technology/.github/.github/actions/git-tag@v0.8.1
        with:
          tag: ${{ needs.metadata.outputs.git_tag }}
